# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{monque}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Backeus"]
  s.date = %q{2010-04-06}
  s.default_executable = %q{monque-web}
  s.description = %q{Like Delayed Job it hath priorities. Like Resque it hath a multitude of queues. Unlike them both it persists on MongoDB.}
  s.email = %q{duztdruid@gmail.com}
  s.executables = ["monque-web"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/monque.rb",
     "lib/monque/job.rb",
     "lib/monque/worker.rb",
     "monque.gemspec",
     "spec/benchmark.rb",
     "spec/db/mongodb-test.conf",
     "spec/job_spec.rb",
     "spec/monque_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/worker_spec.rb"
  ]
  s.homepage = %q{http://github.com/dbackeus/monque}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Like Delayed Job it hath priorities. Like Resque it hath a multitude of queues. Unlike them both it persists on MongoDB.}
  s.test_files = [
    "spec/benchmark.rb",
     "spec/job_spec.rb",
     "spec/monque_spec.rb",
     "spec/spec_helper.rb",
     "spec/worker_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongo>, [">= 0.19.3"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
    else
      s.add_dependency(%q<mongo>, [">= 0.19.3"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<mongo>, [">= 0.19.3"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
  end
end

